### ISSUE TITLE
XML instead of HTML

### ISSUE THREAD

**Issue by aasimenator** [gkpln3/ConfluenceToWikiJS#2]
Hi,

we have confluence data in XML format, is it possible to import it using your tool? we are preparing for a scenario where our confluence server is non-existent and we only have XML backup of the site, can we restore that to something other than confluence like WikiJS?

Thanks

**Comment by gkpln3** [comment]
I afraid not, but you are welcome to try and modify the scripts to make it compatible with that too, or just obtain an HTML backup of your confluence data.
